org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1


mod_id=epicfighttinkercompat
mod_name=Epic Fight Tinker Compat
mod_license=GPL-3.0
mod_version=20.2.6
mod_group_id=com.minhhjjj.epicfighttinkercompat
mod_authors=minhhjjj
mod_description=Make TConstruct works with Epic Fight.